---
title: Mosher & Co. Corp.
email: mosherandcocorp@gmail.com
description: >-
  A family empire; coming soon!
baseurl: ""
url: "https://mosherandcocorp.com/"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll-minifier:
  uglifier_args:
    harmony: true

feed:
  tags: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
